-- SQL Script to Insert Sample Questions for Web Developer Trainee
-- Run this in your Supabase SQL Editor or any PostgreSQL client

-- First, get the topic IDs from question_topics table
-- You can run this query to see available topics:
-- SELECT id, name, category FROM question_topics WHERE is_active = true ORDER BY category, sort_order;

-- Insert sample questions for Web Developer Trainee
-- Job Description ID: 97d508ce-f4f5-4693-b1b9-4b5dcad7475c

INSERT INTO exam_questions (
    id,
    job_description_id,
    question_text,
    question_type,
    question_category,
    difficulty_level,
    mcq_options,
    correct_answer,
    answer_explanation,
    points,
    time_limit_seconds,
    tags,
    topic_id,
    subtopic,
    created_by,
    status,
    hr_notes,
    is_active,
    created_at,
    updated_at
) VALUES 
-- HTML/CSS Fundamentals
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'What does HTML stand for?',
    'mcq',
    'technical',
    'easy',
    '[{"option": "A", "text": "HyperText Markup Language"}, {"option": "B", "text": "High Tech Modern Language"}, {"option": "C", "text": "Home Tool Markup Language"}, {"option": "D", "text": "Hyperlink and Text Markup Language"}]'::jsonb,
    'A',
    'HTML stands for HyperText Markup Language, which is the standard markup language for creating web pages.',
    1,
    30,
    ARRAY['html', 'fundamentals', 'web-development'],
    (SELECT id FROM question_topics WHERE name = 'Web Development' AND category = 'technical' LIMIT 1),
    'Basics',
    'hr',
    'approved',
    'Basic HTML knowledge for web developer trainee',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'Which CSS property is used to change the text color?',
    'mcq',
    'technical',
    'easy',
    '[{"option": "A", "text": "text-color"}, {"option": "B", "text": "color"}, {"option": "C", "text": "font-color"}, {"option": "D", "text": "text-style"}]'::jsonb,
    'B',
    'The CSS property "color" is used to set the color of text content.',
    1,
    30,
    ARRAY['css', 'styling', 'web-development'],
    (SELECT id FROM question_topics WHERE name = 'Web Development' AND category = 'technical' LIMIT 1),
    'Text Styling',
    'hr',
    'approved',
    'Basic CSS knowledge for web developer trainee',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'What is the correct way to create a hyperlink in HTML?',
    'mcq',
    'technical',
    'easy',
    '[{"option": "A", "text": "<link> tag"}, {"option": "B", "text": "<a> tag with href attribute"}, {"option": "C", "text": "<hyperlink> tag"}, {"option": "D", "text": "<url> tag"}]'::jsonb,
    'B',
    'The correct HTML tag for creating hyperlinks is <a> with the href attribute.',
    1,
    30,
    ARRAY['html', 'links', 'web-development'],
    (SELECT id FROM question_topics WHERE name = 'Web Development' AND category = 'technical' LIMIT 1),
    'Links',
    'hr',
    'approved',
    'HTML link creation knowledge',
    true,
    NOW(),
    NOW()
),
-- JavaScript Basics
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'How do you declare a variable in JavaScript?',
    'mcq',
    'technical',
    'easy',
    '[{"option": "A", "text": "var name = \\"John\\""}, {"option": "B", "text": "variable name = \\"John\\""}, {"option": "C", "text": "v name = \\"John\\""}, {"option": "D", "text": "declare name = \\"John\\""}]'::jsonb,
    'A',
    'In JavaScript, variables are declared using var, let, or const keywords.',
    1,
    30,
    ARRAY['javascript', 'variables', 'fundamentals'],
    (SELECT id FROM question_topics WHERE name = 'Programming Languages' AND category = 'technical' LIMIT 1),
    'Variables',
    'hr',
    'approved',
    'Basic JavaScript variable declaration',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'What will be the output of: console.log(2 + 2)?',
    'mcq',
    'technical',
    'easy',
    '[{"option": "A", "text": "22"}, {"option": "B", "text": "4"}, {"option": "C", "text": "2+2"}, {"option": "D", "text": "undefined"}]'::jsonb,
    'B',
    'The output will be 4, as JavaScript performs mathematical addition on the numbers.',
    1,
    30,
    ARRAY['javascript', 'arithmetic', 'fundamentals'],
    (SELECT id FROM question_topics WHERE name = 'Programming Languages' AND category = 'technical' LIMIT 1),
    'Operators',
    'hr',
    'approved',
    'Basic JavaScript arithmetic understanding',
    true,
    NOW(),
    NOW()
),
-- Responsive Design
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'What is responsive web design?',
    'mcq',
    'technical',
    'medium',
    '[{"option": "A", "text": "Designing websites that work on all devices"}, {"option": "B", "text": "Designing websites with bright colors"}, {"option": "C", "text": "Designing websites that load quickly"}, {"option": "D", "text": "Designing websites with animations"}]'::jsonb,
    'A',
    'Responsive web design is an approach that makes web pages render well on a variety of devices and screen sizes.',
    2,
    60,
    ARRAY['responsive-design', 'css', 'mobile'],
    (SELECT id FROM question_topics WHERE name = 'Web Development' AND category = 'technical' LIMIT 1),
    'Responsive Design',
    'hr',
    'approved',
    'Understanding of responsive design concepts',
    true,
    NOW(),
    NOW()
),
-- Git/Version Control
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'What is Git?',
    'mcq',
    'technical',
    'medium',
    '[{"option": "A", "text": "A programming language"}, {"option": "B", "text": "A version control system"}, {"option": "C", "text": "A web browser"}, {"option": "D", "text": "A database management system"}]'::jsonb,
    'B',
    'Git is a distributed version control system used for tracking changes in source code during software development.',
    2,
    60,
    ARRAY['git', 'version-control', 'development'],
    (SELECT id FROM question_topics WHERE name = 'DevOps & Cloud' AND category = 'technical' LIMIT 1),
    'Version Control',
    'hr',
    'approved',
    'Basic understanding of version control',
    true,
    NOW(),
    NOW()
),
-- Problem Solving (Text Questions)
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'Explain the difference between HTML and CSS in web development.',
    'text',
    'technical',
    'medium',
    NULL,
    'HTML provides the structure and content of web pages, while CSS controls the presentation and styling.',
    'HTML (HyperText Markup Language) is used to create the structure and content of web pages, defining elements like headings, paragraphs, and links. CSS (Cascading Style Sheets) is used to control the presentation, layout, and styling of these HTML elements, including colors, fonts, spacing, and positioning.',
    3,
    120,
    ARRAY['html', 'css', 'web-development', 'fundamentals'],
    (SELECT id FROM question_topics WHERE name = 'Web Development' AND category = 'technical' LIMIT 1),
    'HTML vs CSS',
    'hr',
    'approved',
    'Understanding of web development fundamentals',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'Describe what you would do if a website you built is not displaying correctly on mobile devices.',
    'text',
    'technical',
    'medium',
    NULL,
    'This question assesses problem-solving skills and understanding of responsive design debugging.',
    'Good answers should include: 1) Checking viewport meta tag, 2) Testing responsive CSS, 3) Using browser developer tools, 4) Checking for CSS media queries, 5) Testing on actual devices, 6) Validating HTML/CSS syntax.',
    3,
    150,
    ARRAY['responsive-design', 'debugging', 'mobile', 'problem-solving'],
    (SELECT id FROM question_topics WHERE name = 'Web Development' AND category = 'technical' LIMIT 1),
    'Debugging',
    'hr',
    'approved',
    'Problem-solving skills for web development issues',
    true,
    NOW(),
    NOW()
),
-- Aptitude Questions
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'If a website loads in 3 seconds on desktop but 8 seconds on mobile, what could be the main reason?',
    'mcq',
    'aptitude',
    'medium',
    '[{"option": "A", "text": "Mobile internet is always slower"}, {"option": "B", "text": "Images are not optimized for mobile"}, {"option": "C", "text": "Mobile browsers are outdated"}, {"option": "D", "text": "Desktop has more RAM"}]'::jsonb,
    'B',
    'Large, unoptimized images are a common cause of slow mobile loading times.',
    2,
    60,
    ARRAY['performance', 'optimization', 'mobile', 'problem-solving'],
    (SELECT id FROM question_topics WHERE name = 'Problem Solving' AND category = 'aptitude' LIMIT 1),
    'Optimization',
    'hr',
    'approved',
    'Understanding of web performance factors',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'Why is it important to test websites on different browsers?',
    'mcq',
    'aptitude',
    'medium',
    '[{"option": "A", "text": "To make the website look identical everywhere"}, {"option": "B", "text": "To ensure compatibility across different user environments"}, {"option": "C", "text": "To increase website speed"}, {"option": "D", "text": "To reduce development time"}]'::jsonb,
    'B',
    'Different browsers may interpret code differently, so testing ensures the website works for all users.',
    2,
    60,
    ARRAY['browser-compatibility', 'testing', 'web-development'],
    (SELECT id FROM question_topics WHERE name = 'Problem Solving' AND category = 'aptitude' LIMIT 1),
    'Browser Testing',
    'hr',
    'approved',
    'Understanding of cross-browser compatibility',
    true,
    NOW(),
    NOW()
),
-- Behavioral Questions
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'Describe a time when you had to learn a new technology or programming concept. How did you approach it?',
    'text',
    'aptitude',
    'medium',
    NULL,
    'This question assesses learning ability and approach to new technologies.',
    'Look for answers that show: 1) Research and documentation reading, 2) Hands-on practice, 3) Seeking help from others, 4) Building small projects, 5) Persistence and problem-solving approach.',
    3,
    180,
    ARRAY['learning', 'adaptability', 'problem-solving', 'behavioral'],
    (SELECT id FROM question_topics WHERE name = 'Problem Solving' AND category = 'aptitude' LIMIT 1),
    'Learning Ability',
    'hr',
    'approved',
    'Assessment of learning and adaptation skills',
    true,
    NOW(),
    NOW()
),
-- Advanced Technical (Hard Level)
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'What is the difference between == and === in JavaScript?',
    'mcq',
    'technical',
    'hard',
    '[{"option": "A", "text": "== compares values only, === compares values and types"}, {"option": "B", "text": "== is faster than ==="}, {"option": "C", "text": "=== is used for strings only"}, {"option": "D", "text": "There is no difference"}]'::jsonb,
    'A',
    '== performs type coercion and compares values, while === compares both values and data types without coercion.',
    3,
    90,
    ARRAY['javascript', 'operators', 'comparison', 'advanced'],
    (SELECT id FROM question_topics WHERE name = 'Programming Languages' AND category = 'technical' LIMIT 1),
    'Operators',
    'hr',
    'approved',
    'Advanced JavaScript operator knowledge',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    '97d508ce-f4f5-4693-b1b9-4b5dcad7475c',
    'Explain the concept of CSS Flexbox and provide a practical example of when you would use it.',
    'text',
    'technical',
    'hard',
    NULL,
    'Flexbox is a CSS layout method for arranging items in a container.',
    'Flexbox is a one-dimensional layout method for arranging items in rows or columns. It provides efficient alignment and distribution of space among items. Practical uses include: 1) Centering content vertically and horizontally, 2) Creating responsive navigation bars, 3) Building card layouts, 4) Aligning form elements. Example: .container { display: flex; justify-content: center; align-items: center; }',
    4,
    180,
    ARRAY['css', 'flexbox', 'layout', 'advanced'],
    (SELECT id FROM question_topics WHERE name = 'Web Development' AND category = 'technical' LIMIT 1),
    'Layout',
    'hr',
    'approved',
    'Advanced CSS layout understanding',
    true,
    NOW(),
    NOW()
);

-- Verify the inserted questions
SELECT 
    question_text,
    question_type,
    question_category,
    difficulty_level,
    points,
    status
FROM exam_questions 
WHERE job_description_id = '97d508ce-f4f5-4693-b1b9-4b5dcad7475c'
ORDER BY created_at DESC;
